easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\TimeUnit
        - App\Entity\ProductGroup
        - App\Entity\ProductionUnit
        - App\Entity\Restaurant
        - App\Entity\ProductionCapacity
